### ISSUE TITLE
Webpack jQuery dependency

### ISSUE THREAD

**Issue by ra6hi9** [gitbrent/SpRestLib#10]
Hello,
When I am building my application based on sprLib, with npm and webpack, the file included in the build is sprestlib.js which does not contains the Jquery dependency.
import sprLib from 'sprestlib' is including this file instead of sprestlib.bundle.js which contains the jquery dependency.
To bypass this I modified the file sprestlib/package.json:

> "main": "dist/sprestlib.js", --> "main": "dist/sprestlib.bundle.js",

Is this the expected behavior? Do I misunderstood something?
Why don't replace Jquery by a more specific library such as axios, lodash, etc...?

Thank you

**Comment by Dragnucs** [comment]
Simply `import`ing a module wont bring jQuery even if the module depends on it. You still need to explicitly import it like so:

```javascript
const $ = require('jquery')
// Or
import jQuery from 'jquery'
```
Or, you can *shim* the module using [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/) so it is present everywhere. This way is probably better suited for jQuery because it would allow you to map both `$` and `jQuery` to the same instance of jQuery.

**Comment by ra6hi9** [comment]
First part is resolved :)

@gitbrent what about?
> Why don't replace Jquery by a more specific library such as axios, lodash, etc...?

**Comment by Dragnucs** [comment]
Replacing jQuery infavor of axios is a good decision.

Maybe we should make a PR for this, shouldn't we @ra6hi9?

**Comment by gitbrent** [comment]
Hi Guys,

@ra6hi9: the `package.json` file lists "jquery-node" and the library calls `var $ = require("jquery-node");`, so I don't know why you'd be having this issue with webpack.  Wouldn't it use produce a product similar to node?

@Dragnucs: i'm working to move the UI functions to a separate library, so jQuery shouldn't need to be around long.  I'd rather have no dependencies. :)
